2023-02-05 05:14:08,808 INFO    [actors_facade.py(get_by_name:19)] name: robert de niro
2023-02-05 17:59:17,530 INFO    [actors_facade.py(get_by_id:11)] id: 1
2023-02-05 17:59:35,362 INFO    [actors_facade.py(get_by_id:11)] id: 100
2023-02-05 18:01:05,450 INFO    [actors_facade.py(get_by_id:11)] id: 100
2023-02-05 18:01:05,451 ERROR   [actors_facade.py(get_by_id:18)] division by zero
2023-02-05 18:01:33,734 ERROR   [actors_impl.py(get_by_id:21)] division by zero
2023-02-05 18:01:55,069 ERROR   [actors_impl.py(get_by_id:21)] division by zero
2023-02-05 18:53:20,350 INFO    [movies_facade.py(get_by_id:9)] id: 100
2023-02-05 18:53:20,352 ERROR   [movies_facade.py(get_by_id:16)] For many-to-many relationship movies.actors, delete-orphan cascade is normally configured only on the "one" side of a one-to-many relationship, and not on the "many" side of a many-to-one or many-to-many relationship.  To force this relationship to allow a particular "actors" object to be referred towards by only a single "movies" object at a time via the movies.actors relationship, which would allow delete-orphan cascade to take place in this direction, set the single_parent=True flag. (Background on this error at: https://sqlalche.me/e/14/bbf0)
2023-02-05 18:53:23,981 INFO    [movies_facade.py(get_by_id:9)] id: 1
2023-02-05 18:53:23,982 ERROR   [movies_facade.py(get_by_id:16)] One or more mappers failed to initialize - can't proceed with initialization of other mappers. Triggering mapper: 'mapped class movies->movies'. Original exception was: For many-to-many relationship movies.actors, delete-orphan cascade is normally configured only on the "one" side of a one-to-many relationship, and not on the "many" side of a many-to-one or many-to-many relationship.  To force this relationship to allow a particular "actors" object to be referred towards by only a single "movies" object at a time via the movies.actors relationship, which would allow delete-orphan cascade to take place in this direction, set the single_parent=True flag. (Background on this error at: https://sqlalche.me/e/14/bbf0)
2023-02-05 19:03:32,670 INFO    [movies_facade.py(get_by_id:9)] id: 1
2023-02-05 19:07:11,849 INFO    [movies_facade.py(get_by_id:9)] id: 100
2023-02-05 19:07:16,134 INFO    [movies_facade.py(get_by_id:9)] id: 99
2023-02-05 19:21:04,381 INFO    [movies_facade.py(delete_by_id:57)] id: 99
2023-02-05 19:27:41,224 INFO    [movies_facade.py(delete_by_id:57)] id: 99
2023-02-05 19:29:50,637 INFO    [movies_facade.py(delete_by_id:57)] id: 99
2023-02-05 19:32:55,519 INFO    [movies_facade.py(delete_by_id:57)] id: 99
2023-02-05 19:43:09,680 INFO    [movies_facade.py(get_by_id:9)] id: 99
2023-02-05 19:43:17,024 INFO    [movies_facade.py(get_by_id:9)] id: 1
2023-02-05 19:43:17,030 ERROR   [movies_impl.py(get_by_id:19)] __repr__ returned non-string (type dict)
2023-02-05 19:51:36,849 INFO    [movies_facade.py(get_by_id:9)] id: 1
2023-02-05 19:51:36,860 ERROR   [movies_impl.py(get_by_id:19)] __repr__ returned non-string (type dict)
2023-02-05 19:52:41,051 INFO    [movies_facade.py(get_by_id:9)] id: 1
2023-02-05 19:55:29,018 INFO    [movies_facade.py(get_by_id:9)] id: 5
